baseURL = "https://scott2000jones.github.io"
publishDir = "../"
languageCode = "en-gb"
title = "Scott Jones"
theme = "avicenna"
timeout=3000

[params]
  cv_name= "cv.pdf"

[[params.affilation]]
  name = "University of St Andrews"
  position = "Computer Science MSci Student"
  contact = "scott2000jones@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/scott2000jones"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/scott2000jones/"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:scott2000jones@gmail.com"


[[params.introduction.paragraph]]
  text="""
  I'm a Computer Science student at the University of St Andrews, on the undergraduate integrated Masters track. I started in 2019, and I'm on track to graduate in 2023 with a Master in Science (MSci) in Computer Science.
  """
[[params.introduction.paragraph]]
  text="""
  This site has quick links to my GitHub, LinkedIn, and my CV, which gives a complete summary of my work and experience so far. Most of my work for my degree has been in C, Java, and Python, although I also have experience in Haskell, Go, and JavaScript, in particular with the React framework.
  """

# [[params.introduction.paragraph]]
#   text="""
#   I have just finished a federated social media website which I worked on throughout this academic year with my team for our CS3099 Software Engineering Team Project module. Our site was built with React and Django, and featured real-time messaging and video calling as well as complete federation of content with other sites using a bespoke protocol developed collaboratively with other teams.
#   """
# [[params.introduction.paragraph]]
#   text="""
#   I also recently worked on a set of Shakespearean Discord Bots with a team as our submission for STACSHACK 2021, where we won the 3rd place prize overall. We created Recurrent Neural Network models using Python and textgenrnn and trained them on archetypal characters from Shakespeare scripts, then we wrote Discord Bots using the Discord API to generate novel text and act out a brand new play in real-time.
#   """
# [[params.introduction.paragraph]]
#   text="""
#   In the very near future I am looking forward to joining American Express as a Technology Intern for the summer, and I am also eager to pursue personal projects this summer too, particularly in the visualisation of cryptography and in cryptocurrency trading.
#   """
  
