baseURL = ""
publishDir = "../"
languageCode = "en-gb"
title = "Scott Jones"
theme = "avicenna"
timeout=3000

[params]
  subtitle= "Computer Science student at the University of St Andrews"
  interests="Deep Reinforcement Learning, Machine Learning "
  cv_name= "cv.pdf"

[[params.affilation]]
  name = "University of St Andrews"
  position = "Computer Science MSci Student"
  contact = "scott2000jones@gmail.com"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/scott2000jones"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/scott2000jones/"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:scott2000jones@gmail.com"


[[params.introduction.paragraph]]
  text="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	 Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Integer feugiat scelerisque varius morbi enim.
	  A diam maecenas sed enim ut sem viverra. Orci eu lobortis elementum nibh tellus.
		Egestas sed sed risus pretium quam vulputate dignissim suspendisse in.
		Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Condimentum lacinia quis vel eros donec.
   """
[[params.introduction.paragraph]]
  text=""" Pellentesque nec nam aliquam sem et tortor consequat id porta.
	Viverra suspendisse potenti nullam ac. Leo vel orci porta non pulvinar neque laoreet.
	Nulla facilisi nullam vehicula ipsum a arcu. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse.
	Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Dui sapien eget mi proin sed libero.
	Quam pellentesque nec nam aliquam sem et tortor consequat id. Aliquet lectus proin nibh nisl.
  """
